name: 'Run action'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'dist/**'
      - 'package*.json'
      - 'action.json'

jobs:
  setup-version:
    name: 'Setup version'

    strategy:
      matrix:
        system:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.system }}

    steps:
      - name: Setup Ninja
        id: setup-ninja
        uses: imesense/gha-setup-ninja@747685d54dcf8adbd5d4aba0858ab7ef64c22398
        with:
          version: '1.12.1'

      - name: Print version
        run: |
          ninja --version

  setup-latest:
    name: 'Setup latest'

    strategy:
      matrix:
        system:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.system }}

    steps:
      - name: Setup Ninja
        id: setup-ninja
        uses: imesense/gha-setup-ninja@747685d54dcf8adbd5d4aba0858ab7ef64c22398

      - name: Print version
        run: |
          ninja --version
