name: 'Run action'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'dist/**'
      - 'package*.json'
      - 'action.json'

jobs:
  run-action:
    name: 'Run action'

    strategy:
      matrix:
        system:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.system }}

    steps:
      - name: Setup Ninja
        id: setup-ninja
        uses: imesense/gha-setup-ninja@d6f2b444ac6afd42599867e6d3334140cd9c27b2
        with:
          version: '1.12.1'

      - name: Print version
        run: |
          ninja --version
